services:
  db-postgres:
    container_name: srk-postgres
    #image: postgres]
    build:
      dockerfile: ./docker/Dockerfile.db-postgres
      context: ../
    environment:
      POSTGRES_DB: sportsrk
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - /srk-postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matheus -d sportsrk"]
      interval: 5s
      timeout: 5s
      retries: 5