services:  
  app:
    container_name: srk-main
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: amthreis/sportsrk-main:compose
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-postgres
      - db-redis
    #command: npm run pre-build-seed; npm run dev

  db-redis:
    container_name: srk-redis
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /srk-redis_data:/data

  db-postgres:
    container_name: srk-postgres
    image: postgres
    environment:
      POSTGRES_DB: sportsrk
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432
    volumes:
      - /srk-postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matheus -d sportsrk"]
      interval: 5s
      timeout: 5s
      retries: 5
    